logging:
  level: "debug"
  mode: "w"
  encoding: "utf-8"

data_src_path: "dataset/processed/val/"
model_src_path: "models/enough_model_pipeline"
dest_dir: "dataset/inference/val"

load_target: true

target_col: "rate"

use_features:
  - "valid_miles"
  - "transport_type"
  - "weight"
  - "origin_kma"
  - "destination_kma"
  - "pickup_year"
  - "pickup_month"
  - "pickup_weekday"
